testing circleci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -42,6 +42,10 @@ jobs:
           name: Copy yarn.lock to correct location
           command: cp ~/circleci-databases/databases/yarn.lock ~/circleci-databases/yarn.lock
 
+      - run:
+          name: Copy package.json to correct location
+          command: cp ~/circleci-databases/databases/package.json ~/circleci-databases/package.json
+
       - restore_cache:
           keys:
             - gem-cache-{{ checksum "Gemfile.lock" }}
@@ -88,17 +92,17 @@ jobs:
           name: Verify Yarn Installation Path
           command: ls -la node_modules
 
-      - run:
-          name: Manually Install Turbolinks
-          command: yarn add turbolinks
+      # - run:
+      #     name: Manually Install Turbolinks
+      #     command: yarn add turbolinks
 
-      - run:
-          name: Verify Turbolinks Installation
-          command: |
-            if [ ! -d "node_modules/turbolinks" ]; then
-              echo "Turbolinks not found!"
-              exit 1
-            fi
+      # - run:
+      #     name: Verify Turbolinks Installation
+      #     command: |
+      #       if [ ! -d "node_modules/turbolinks" ]; then
+      #         echo "Turbolinks not found!"
+      #         exit 1
+      #       fi
 
       - run:
           name: Precompile assets
